language: ruby
rvm:
  - 2.1.5
gemfile:
  - Gemfile
env:
  - DB=postgresql
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database rdaily_test;' -U postgres
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate
  - bundle exec rspec spec/
