language: ruby
rvm:
  - 2.0.0
gemfile:
  - Gemfile
env:
  - DB=sqlite3
before_script:
  - sudo apt-get install postgresql-contrib
  - sudo /etc/init.d/postgresql restart
  - psql -c 'create database rdaily_test;' -U postgres
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/
notifications:
  emails:
    - ryohashimoto@gmail.com
  on_success: always
  on_failure: always