language: ruby
rvm:
  - 2.1.3
gemfile:
  - Gemfile
env:
  - DB=mysql
before_script:
  - mysql -e 'create database rdaily_test'
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate
  - bundle exec rspec spec/
notifications:
  emails:
    - ryohashimoto@gmail.com
  on_success: always
  on_failure: always
