language: ruby
rvm:
  - 2.5.3
gemfile:
  - Gemfile
env:
  - DB=postgresql
addons:
  postgresql: "9.4"
before_script:
  - psql -c 'create database rdaily_test;' -U postgres
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate
  - bundle exec rspec spec/
