development:
  adapter: postgresql
  encoding: unicode
  database: rdaily_development
  pool: 5
  username: ryo
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: rdaily_test
  pool: 5
  username: ryo
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: rdaily_production
  pool: 5
  username: ryo
  password:
